### ISSUE TITLE
swagger-client@3.3.0  broke

### ISSUE THREAD

**Issue by srl295** [IBM-Bluemix/gp-js-client#104]
https://github.com/swagger-api/swagger-js/releases/tag/v3.3.0

```
/Users/srl/src/gp-js-client/node_modules/swagger-client/dist/index.js:1
(function (exports, require, module, __filename, __dirname) { module.exports=function(e){function t(n){if(r[n])return r[n].exports;var a=r[n]={i:n,l:!1,exports:{}};return e[n].call(a.exports,a,a.exports,t),a.l=!0,a.exports}var r={};return t.m=e,t.c=r,t.i=function(e){return e},t.d=function(e,r,n){t.o(e,r)||Object.defineProperty(e,r,{configurable:!1,enumerable:!0,get:n})},t.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(r,"a",r),r},t.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},t.p="",t(t.s=53)}([function(e,t){e.exports=require("babel-runtime/core-js/object/keys")},function(e,t){e.exports=require("babel-runtime/core-js/object/assign")},function(e,t){e.exports=require("babel-runtime/helpers/typeof")},function(e,t,r){"use strict";function n(e){return e&&e.__esModule?e:{default:e}}function a(e){var t=e.openapi;return!!t&&(0,k.default)(t,"3")}function u(e){var t=e.swagger;

TypeError: Cannot read property 'content-type' of undefined
    at a (/Users/srl/src/gp-js-client/node_modules/swagger-client/dist/index.js:1:3864)
    at /Users/srl/src/gp-js-client/node_modules/swagger-client/dist/index.js:1:27329
    at Function.o [as resolve] (/Users/srl/src/gp-js-client/node_modules/swagger-client/dist/index.js:1:28249)
    at a.resolve (/Users/srl/src/gp-js-client/node_modules/swagger-client/dist/index.js:1:12954)
    at a (/Users/srl/src/gp-js-client/node_modules/swagger-client/dist/index.js:1:12126)
    at Client.createSwaggerClient (/Users/srl/src/gp-js-client/lib/client.js:109:27)
    at new Client (/Users/srl/src/gp-js-client/lib/client.js:74:21)
    at Object.getClient (/Users/srl/src/gp-js-client/lib/main.js:39:10)
    at Object.<anonymous> (/Users/srl/src/gp-js-client/test/partner-test.js:33:23)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at /Users/srl/src/gp-js-client/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/srl/src/gp-js-client/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/srl/src/gp-js-client/node_modules/mocha/lib/mocha.js:513:10)
    at Object.<anonymous> (/Users/srl/src/gp-js-client/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
```

**Comment by srl295** [comment]
bisect points to 060b7913ac0e3e16dbc812459ee8e15bb07ce9be
